---
title: "Analysis of bile acids data"
author: "Timothy Yu"
output: 
  github_document:
    toc: true
    html_preview: false
editor_options:
  chunk_output_type: inline
---
This notebook analyzes the bile acids dataset.
```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggfortify)
require(cowplot)
theme_set(theme_cowplot())
source('utils/utils.R')
```

```{r}
sessionInfo()
```

```{r}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")))
```

Read in bile acids dataset.
```{r}
BA_totalpool = read.csv('../processed_data/datasets/BA_totalpool.csv', header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
```

PCA plot of bile acids data.
```{r, ba1, echo=T, fig.width=6, fig.height=4, fig.align="center", dpi=300, dev="png"}
autoplot(prcomp(BA_totalpool[-c(1,2)], scale. = TRUE), data = BA_totalpool, colour = 'Treatment', size = 2.5) + scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))

#ggsave('../figures/bile_acids_totalpool_pca.pdf', height = 3.5, width = 5)
```

Bubble plot showing relative fold-change in bile acids.
```{r, ba2, echo=T, fig.width=10, fig.height=5, fig.align="center", dpi=300, dev="png"}
BA_totalpool_sub = BA_totalpool %>% dplyr::select(
  ID, Treatment,
  `T-a-MCA`, `T-b-MCA`, `T-o-MCA`, `TCDCA`, `TCA`, `TDCA`, `TLCA`, `b-MCA`, `CA`
)

bubdata = makeBubbleData(BA_totalpool_sub)
bubp = getBubbleSignificance(bubdata)
makeBubblePlot(bubp, abundance=FALSE)

#ggsave('../figures/bile_acids_bubble_plot.pdf', height = 4, width = 13)
#write.csv(bubp, '../../ba_bubble_significance.csv')
```

```{r}
options(scipen=999)
percent_BA = BA_totalpool %>% 
  gather("bile_acid", "abundance", -c(ID, Treatment)) %>%
  group_by(Treatment, bile_acid) %>%
  mutate(median_abundance = median(abundance)) %>%
  select(Treatment, bile_acid, median_abundance) %>%
  ungroup() %>%
  distinct() %>%
  group_by(Treatment) %>%
  mutate(total_abundance = sum(median_abundance)) %>%
  mutate(percent_bile_acid = (median_abundance / total_abundance) * 100)
```

```{r}
# rmarkdown::render("bile_acids.Rmd")
# mv bile_acids.md ../markdowns/
# mv bile_acids_files ../markdowns/
```


