---
title: "Significant Lipids correlated with top RNA-seq genes"
author: "Timothy Yu"
date: "6/24/24"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
require(cowplot)
theme_set(theme_cowplot())
```

```{r}
top50gene_x_liver_lipid = read.csv('../processed_data/correlations/top50gene_x_liver_lipid.csv', 
                                   header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
```

```{r}
# too many lipids, so figure out which ones are most abundant
lipid_abundance = read.csv('../processed_data/datasets/Lipidomics_liver.csv', header = TRUE,
                     stringsAsFactors = FALSE, check.names = FALSE) %>%
  pivot_longer(cols = -c(ID, Treatment),
               names_to = "Lipid",
               values_to = "Abundance") %>%
  group_by(Lipid) %>%
  mutate(Max_abundance = max(Abundance, na.rm = TRUE)) %>%
  ungroup() %>%
  select(Lipid, Max_abundance) %>%
  distinct()
```

```{r}
top50gene_x_liver_lipid_filtered = top50gene_x_liver_lipid %>% 
  mutate(abs_bicor = abs(bicor)) %>%
  filter(abs_bicor > 0.6, adj_pval < 0.05) %>%
  group_by(Liver_lipid) %>%
  mutate(Num_significant_corrs = n()) %>%
  ungroup() %>%
  mutate(Lipid_class = ifelse(grepl("^PE\\.O\\.|^PE\\.P\\.", Liver_lipid),
                              sub("\\.", "_", str_extract(Liver_lipid, "^PE\\..")),
                              str_extract(Liver_lipid, "^[^.]+"))) %>% drop_na() %>%
  left_join(., lipid_abundance, by = c("Liver_lipid"="Lipid")) %>%
  filter(Gene %in% c('Apom', 'Apoa4', 'Cd36', 'Cidec', 'Fabp2', 'Abcd1', 'Mogat1', 'Lgals1', 'Osbpl3')) %>%
  filter(Max_abundance > 0.3)

#lipids_to_keep = (top50gene_x_liver_lipid_filtered %>% 
 # select(Liver_lipid, Lipid_class, Max_abundance) %>% 
  #distinct() %>%
  #group_by(Lipid_class) %>%
  #slice_max(order_by = Max_abundance, n = 10) %>%
  #ungroup())$Liver_lipid

top50gene_x_liver_lipid_filtered = top50gene_x_liver_lipid_filtered %>% 
  filter(Liver_lipid %in% lipids_to_keep)

length(unique(top50gene_x_liver_lipid_filtered$Liver_lipid))
length(unique(top50gene_x_liver_lipid_filtered$Gene))

write.csv(top50gene_x_liver_lipid_filtered,
          '../processed_data/misc/plot_sig_top50gene_x_liver_lipid.csv', row.names = FALSE, quote = FALSE)
```

```{r}
osbpl3_corrs = top50gene_x_liver_lipid %>%
  filter(Gene == 'Osbpl3') %>%
  drop_na() %>%
  mutate(abs_bicor = abs(bicor)) %>%
  filter(abs_bicor > 0.7, adj_pval < 0.05) %>%
  left_join(., lipid_abundance, by = c("Liver_lipid"="Lipid")) %>%
  filter(Max_abundance > 0.1) %>%
  mutate(Lipid_class = ifelse(grepl("^PE\\.O\\.|^PE\\.P\\.", Liver_lipid),
                              sub("\\.", "_", str_extract(Liver_lipid, "^PE\\..")),
                              str_extract(Liver_lipid, "^[^.]+")),
         Lipid_formatted = ifelse(Lipid_class == "CE", 
                                  paste0("CE(", sub("\\.", ":", sub("CE\\.", "", Liver_lipid)), ")"),
                            ifelse(Lipid_class == "DG",
                                  paste0("DG(", gsub("\\.", ":", sub("_", "/", sub("DG\\.", "", Liver_lipid))), ")"),
                            ifelse(Lipid_class == "PC",
                                  paste0("PC(", gsub("\\.", ":", sub("_", "/", sub("PC\\.", "", Liver_lipid))), ")"),
                            ifelse(Lipid_class == "PE",
                                  paste0("PE(", gsub("\\.", ":", sub("_", "/", sub("PE\\.", "", Liver_lipid))), ")"),
                            ifelse(Lipid_class == "TG",
                                  paste0("TG(", sub("\\..*FA.*", "", sub("\\.", ":", sub("TG\\.", "", Liver_lipid))), ")"),
                            ifelse(Lipid_class == "SM",
                                  paste0("SM(", sub("\\.", ":", sub("\\.", "/", sub("SM\\.", "", Liver_lipid))), ")"),
                                  Liver_lipid))))))) %>%
  mutate(Lipid_formatted = ifelse(Lipid_class == "SM", 
                                  paste0("SM(", gsub("\\.", "/", gsub("([0-9]+)\\.", "\\1:", gsub("(d[0-9]+\\.[0-9]+)\\.(.*)", "\\1/\\2", sub("SM\\.", "", Liver_lipid)))), ")"),
                                  Lipid_formatted))

lipids = osbpl3_corrs %>% select(Lipid_formatted) %>% distinct()
write.csv(lipids,
          '../processed_data/misc/osbpl3_signficant_lipids.csv', row.names = FALSE, quote = FALSE)
```

```{r}
osbpl3_corrs = top50gene_x_liver_lipid %>%
  filter(Gene == 'Osbpl3') %>%
  drop_na() %>%
  mutate(abs_bicor = abs(bicor)) %>%
  left_join(., lipid_abundance, by = c("Liver_lipid"="Lipid")) %>%
  mutate(Lipid_class = ifelse(grepl("^PE\\.O\\.|^PE\\.P\\.", Liver_lipid),
                              sub("\\.", "_", str_extract(Liver_lipid, "^PE\\..")),
                              str_extract(Liver_lipid, "^[^.]+")),
         Lipid_formatted = ifelse(Lipid_class == "CE", 
                                  paste0("CE ", sub("\\.", ":", sub("CE\\.", "", Liver_lipid))),
                            ifelse(Lipid_class == "DG",
                                  paste0("DG ", gsub("\\.", ":", sub("_", "_", sub("DG\\.", "", Liver_lipid)))),
                            ifelse(Lipid_class == "PC",
                                  paste0("PC ", gsub("\\.", ":", sub("_", "_", sub("PC\\.", "", Liver_lipid)))),
                            ifelse(Lipid_class == "PE",
                                  paste0("PE ", gsub("\\.", ":", sub("_", "_", sub("PE\\.", "", Liver_lipid)))),
                            ifelse(Lipid_class == "TG",
                                  paste0("TG ", sub("\\.FA", "-FA", sub("\\.", ":", sub("(\\d+)\\.(\\d+)\\.FA", "\\1:\\2-FA", sub("TG\\.", "", Liver_lipid))))),
                            ifelse(Lipid_class == "LacCER",
                                  paste0("LacCER ", gsub("\\.", ":", sub("LacCER\\.d(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)", "d\\1:\\2/\\3:\\4", Liver_lipid))),
                            ifelse(Lipid_class == "PE_O",
                                  paste0("PE O-", sub("(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)", "\\1:\\2/\\3:\\4", sub("PE\\.O\\.", "", Liver_lipid))),
                            ifelse(Lipid_class == "PE_P",
                                  paste0("PE P-", sub("(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)", "\\1:\\2/\\3:\\4", sub("PE\\.P\\.", "", Liver_lipid))),
                                  Liver_lipid)))))))))
```

```{r}
# this is for making the Osbpl3 network figure!
library(readxl)

# Function to extract the number of double bonds from FA part
get_double_bonds <- function(lipid) {
  as.numeric(gsub(".*FA\\d+:(\\d+).*", "\\1", lipid))
}

osbpl3_crispr_data = read_excel('../raw_data/excel/20210623_Exp1_ETV203_Osbpl3.xlsx', 
                                sheet = "Signif Species") %>%
  rename(Liver_lipid = `...1`) %>% 
  left_join(., osbpl3_corrs, by=c('Liver_lipid'='Lipid_formatted')) %>%
  drop_na() %>%
  mutate(significant_corr = ifelse(adj_pval < 0.05, "yes", "no")) %>%
  mutate(fold_change = `Mean of Osbpl3 CRISPR` / `Mean of Control CRISPR`) %>%
  mutate(Gene = 'Osbpl3') %>%
  mutate(chain_length = ifelse(
    Lipid_class == "TG", 
    as.numeric(sub(".*-FA(\\d+):.*", "\\1", Liver_lipid)), "N/A")
  ) %>%
  mutate(chain_class = ifelse(chain_length %in% c(14, 15), "medium chain",
                       ifelse(chain_length %in% c(16, 17, 18), "long chain",
                       ifelse(chain_length %in% c(20, 22), "very long chain", "N/A")))) %>%
  mutate(saturation = ifelse(Lipid_class == "TG",
    case_when(
      get_double_bonds(Liver_lipid) >= 2 ~ "PUFA",
      get_double_bonds(Liver_lipid) == 1 ~ "MUFA",
      get_double_bonds(Liver_lipid) == 0 ~ "SFA",
      TRUE ~ "Unknown"
    ), "N/A")
  ) %>%
  mutate(TG_class = paste(chain_class, saturation, sep = " + "))

write.csv(osbpl3_crispr_data, '../processed_data/misc/ETV203_Osbpl3_data.csv', row.names = FALSE, quote = FALSE)
```

```{r}
osbpl3_crispr_data %>% drop_na() %>% 
  ggplot(aes(x=log10(`Mean of Control CRISPR`))) + geom_density(aes(fill=significant_corr), alpha=0.3)
```