---
title: "Fig5"
output: html_document
---

```{r, include = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
require(cowplot)
theme_set(theme_cowplot())
library(viridis)
library(RColorBrewer)
library(WGCNA)
#library(NMF)
```

### loading in data and processing 

```{r}
# load in FPKM RNA-seq data
all_genes = read.csv('../processed_data/data_tables/RNA-seq-FPKM-with-gene-names.csv', header = TRUE, row.names = 1)

# load in liver lipid data
liverlipids = read.csv('../processed_data/data_tables/lipidomics_liver_clean.csv', header = TRUE, row.names = 1)

# load in plasma data
plasmalipids = read.csv('../processed_data/data_tables/lipidomics_plasma_clean.csv', header = TRUE, row.names = 1)
```

```{r}
# merging RNA-seq and liver lipidomics by same identifier. We will merge by the lipidomics ID.
head(all_genes, 3)
head(liverlipids, 3)

# load in mapping file for RNA-seq and Lipidomics ID's
rnaseq_mapping_list = read.table('~/Desktop/ETV007/raw_data/rnaseq_mapping_list.txt', header = TRUE, stringsAsFactors = FALSE)

medians = data.frame("Median" = apply(all_genes, 2, median, na.rm = T)) %>% tibble::rownames_to_column(var = "Gene") %>% filter(Median > 0.1)

# filter genes by FPKM > 0.1 and tag them with the lipidomics ID
filtered_genes = all_genes %>% dplyr::select(medians$Gene) %>% tibble::rownames_to_column(var = "RNA_seq_ID") %>% left_join(., rnaseq_mapping_list, by = "RNA_seq_ID")

ordered_lipidomics_ID = filtered_genes$Lipidomics_ID
ordered_liverlipids = liverlipids %>% tibble::rownames_to_column(var = "Lipidomics_ID") %>% filter(Lipidomics_ID %in% ordered_lipidomics_ID)
setdiff(ordered_lipidomics_ID, ordered_liverlipids$Lipidomics_ID) # remove WD4_39 from RNA-seq data
ordered_geneData = filtered_genes %>% filter(Lipidomics_ID != 'WD4_39') %>% arrange(factor(Lipidomics_ID, levels = ordered_liverlipids$Lipidomics_ID))

# data is ordered! remove non quantitative columns
ordered_liverlipids = ordered_liverlipids %>% dplyr::select(-Lipidomics_ID)
ordered_geneData_for_liver = ordered_geneData %>% dplyr::select(-RNA_seq_ID, -Lipidomics_ID)
```

```{r}
# merging RNA-seq and plasma lipidomics by same identifier. We will merge by the lipidomics ID.
head(all_genes, 3)
head(plasmalipids, 3)

# use same filtered genes by FPKM > 0.1 from above and tag them with the lipidomics ID
ordered_lipidomics_ID = filtered_genes$Lipidomics_ID
ordered_plasmalipids = plasmalipids %>% tibble::rownames_to_column(var = "Lipidomics_ID") %>% filter(Lipidomics_ID %in% ordered_lipidomics_ID)

ordered_geneData = filtered_genes %>% arrange(factor(Lipidomics_ID, levels = plasmalipids$Lipidomics_ID))

# check that data is ordered
assertthat::are_equal(ordered_geneData$Lipidomics_ID, ordered_plasmalipids$Lipidomics_ID)

ordered_geneData$Lipidomics_ID
ordered_plasmalipids$Lipidomics_ID

# data is ordered! remove non quantitative columns
ordered_plasmaData = ordered_plasmaData %>% dplyr::select(-Lipidomics_ID, -Treatment)
ordered_geneData2 = ordered_geneData2 %>% dplyr::select(-RNA_seq_ID, -Lipidomics_ID)
```

```{r}
# merging liver and plasma lipidomics by same identifier. We will merge by the lipidomics ID.
head(complete_liverData, 3)
head(complete_plasmaData, 3)

# load in mapping file for RNA-seq and Lipidomics ID's
rnaseq_mapping_list = read.table('~/Desktop/ETV007/raw_data/rnaseq_mapping_list.txt', header = TRUE, stringsAsFactors = FALSE)

medians = data.frame("Median" = apply(all_genes, 2, median, na.rm = T)) %>% tibble::rownames_to_column(var = "Gene") %>% filter(Median > 0.1)

# filter genes by FPKM > 0.1 and tag them with the lipidomics ID
filtered_genes = all_genes %>% dplyr::select(medians$Gene) %>% tibble::rownames_to_column(var = "RNA_seq_ID") %>% left_join(., rnaseq_mapping_list, by = "RNA_seq_ID")

ordered_lipidomics_ID = filtered_genes$Lipidomics_ID
ordered_plasmaData = complete_plasmaData %>% tibble::rownames_to_column(var = "Lipidomics_ID") %>% filter(Lipidomics_ID %in% ordered_lipidomics_ID)
bio
ordered_geneData2 = filtered_genes %>% arrange(factor(Lipidomics_ID, levels = ordered_plasmaData$Lipidomics_ID))

# check that data is ordered
assertthat::are_equal(ordered_geneData2$Lipidomics_ID, ordered_plasmaData$Lipidomics_ID)

# data is ordered! remove non quantitative columns
ordered_plasmaData = ordered_plasmaData %>% dplyr::select(-Lipidomics_ID, -Treatment)
ordered_geneData2 = ordered_geneData2 %>% dplyr::select(-RNA_seq_ID, -Lipidomics_ID)
```
### Analysis of data ===============================================================================================================

```{r}
# genes and liver lipids
corr = bicorAndPvalue(ordered_geneData, ordered_liverData)

# Function that creates table with all gene-lipid correlations/p-values that pass a specified adjusted significance threshold.
createCorrTable <- function(corr_object, threshold) {
  
  bicor <- corr$bicor
  p <- corr$p

  x <- bicor %>% as.data.frame() %>%
  tibble::rownames_to_column(var = 'Gene') %>%
  gather(Lipid, Bicor, 2:ncol(.))
    
  y <- p %>% as.data.frame() %>%
  tibble::rownames_to_column(var = 'Gene') %>%
  gather(Lipid, Pval, 2:ncol(.)) %>%
  mutate(Adj_P = p.adjust(Pval, method = 'BH', n = length(Pval)))

  table <- left_join(x, y, by = c('Gene', 'Lipid')) %>%
    dplyr::select(Gene, Lipid, Bicor, Adj_P) %>%
    filter(Adj_P < threshold)
  return(table)
}

corrTable = createCorrTable(corr, 0.05)
write.table(corrTable, '~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-corrTable_FDR<0.05.txt', sep = '\t', row.names = FALSE, quote = FALSE)
```

```{r}
# genes and plasma lipids
corr = bicorAndPvalue(ordered_geneData2, ordered_plasmaData)

corrTable = createCorrTable(corr, 0.05)
write.table(corrTable, '~/Desktop/ETV007/processed_data/GENE-PLASMALIPID-corrTable_FDR<0.05.txt', sep = '\t', row.names = FALSE, quote = FALSE)
```

# frequency and fractions for liver =========================

```{r}
# sort by number of significant correlations in total or by lipid class
freqTable = corrTable %>% group_by(Gene) %>% mutate(Total = n()) %>% ungroup() %>%
  separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  group_by(Gene) %>% mutate(num_TAG = sum(grepl('TAG', Class)),
                            num_DAG = sum(Class == 'DAG'),
                            num_CE = sum(Class == 'CE'),
                            num_CER = sum(Class == 'CER'),
                            num_FFA = sum(Class == 'FFA'),
                            num_HCER = sum(Class == 'HCER'),
                            num_LPC = sum(Class == 'LPC'),
                            num_LPE = sum(Class == 'LPE'),
                            num_PC = sum(Class == 'PC'),
                            num_PE = sum(Class == 'PE'),
                            num_SM = sum(Class == 'SM')) %>% ungroup() %>%
  dplyr::select(-c(Lipid, Class, Bicor, Adj_P)) %>% distinct()
```

```{r}
# sort by fraction of significant correlations in total or by lipid class
Lipids = colnames(filtered_liverData) 
total_TAG = sum(grepl("TAG", Lipids)) # 394
total_DAG = sum(grepl("DAG", Lipids)) # 11
total_CE = sum(grepl("CE", Lipids)) - sum(grepl("CER", Lipids)) # 13
total_CER = sum(grepl("CER", Lipids)) - sum(grepl("HCER", Lipids)) # 7
total_FFA = sum(grepl("FFA", Lipids)) # 26
total_HCER = sum(grepl("HCER", Lipids)) # 6
total_LPC = sum(grepl("LPC", Lipids)) # 8
total_LPE = sum(grepl("LPE", Lipids)) # 9
total_PC = sum(grepl("PC", Lipids)) - sum(grepl("LPC", Lipids)) # 44
total_PE = sum(grepl("PE", Lipids)) - sum(grepl("LPE", Lipids)) # 46
total_SM = sum(grepl("SM", Lipids)) # 12

assertthat::are_equal(total_TAG+total_DAG+total_CE+total_CER+total_FFA+total_HCER+total_LPC+total_LPE+total_PC+total_PE+total_SM, length(Lipids))

fracTable = corrTable %>% group_by(Gene) %>% mutate(Total = n()) %>% ungroup() %>%
  separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  group_by(Gene) %>% mutate(frac_TAG = sum(grepl('TAG', Class)/total_TAG),
                            frac_DAG = sum(Class == 'DAG')/total_DAG,
                            frac_CE = sum(Class == 'CE')/total_CE,
                            frac_CER = sum(Class == 'CER')/total_CER,
                            frac_FFA = sum(Class == 'FFA')/total_FFA,
                            frac_HCER = sum(Class == 'HCER')/total_HCER,
                            frac_LPC = sum(Class == 'LPC')/total_LPC,
                            frac_LPE = sum(Class == 'LPE')/total_LPE,
                            frac_PC = sum(Class == 'PC')/total_PC,
                            frac_PE = sum(Class == 'PE')/total_PE,
                            frac_SM = sum(Class == 'SM')/total_SM) %>% ungroup() %>%
  dplyr::select(-c(Lipid, Class, Bicor, Adj_P)) %>% distinct()
```

```{r}
# write as csv files
write.csv(corrTable, '~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-corrTable_FDR<0.05.csv', row.names = FALSE, quote = FALSE)
write.csv(freqTable, '~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-freqTable_FDR<0.05.csv', row.names = FALSE, quote = FALSE)
write.csv(fracTable, '~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-fracTable_FDR<0.05.csv', row.names = FALSE, quote = FALSE)
```

# frequency and fractions for plasma =========================

```{r}
# sort by number of significant correlations in total or by lipid class
freqTable = corrTable %>% group_by(Gene) %>% mutate(Total = n()) %>% ungroup() %>%
  separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  group_by(Gene) %>% mutate(num_TAG = sum(grepl('TAG', Class)),
                            num_DAG = sum(Class == 'DAG'),
                            num_CE = sum(Class == 'CE'),
                            num_CER = sum(Class == 'CER'),
                            num_FFA = sum(Class == 'FFA'),
                            num_HCER = sum(Class == 'HCER'),
                            num_LPC = sum(Class == 'LPC'),
                            num_LPE = sum(Class == 'LPE'),
                            num_PC = sum(Class == 'PC'),
                            num_PE = sum(Class == 'PE'),
                            num_SM = sum(Class == 'SM')) %>% ungroup() %>%
  dplyr::select(-c(Lipid, Class, Bicor, Adj_P)) %>% distinct()
```

```{r}
# sort by fraction of significant correlations in total or by lipid class
Lipids = colnames(complete_plasmaData[,-ncol(complete_plasmaData)]) 
total_TAG = sum(grepl("TAG", Lipids)) # 149
total_DAG = sum(grepl("DAG", Lipids)) # 6
total_CE = sum(grepl("CE", Lipids)) - sum(grepl("CER", Lipids)) # 26
total_CER = sum(grepl("CER", Lipids)) - sum(grepl("HCER", Lipids)) # 4
total_FFA = sum(grepl("FFA", Lipids)) # 26
total_HCER = sum(grepl("HCER", Lipids)) # 6
total_LPC = sum(grepl("LPC", Lipids)) # 13
total_LPE = sum(grepl("LPE", Lipids)) # 2
total_PC = sum(grepl("PC", Lipids)) - sum(grepl("LPC", Lipids)) # 30
total_PE = sum(grepl("PE", Lipids)) - sum(grepl("LPE", Lipids)) # 0
total_SM = sum(grepl("SM", Lipids)) # 12

assertthat::are_equal(total_TAG+total_DAG+total_CE+total_CER+total_FFA+total_HCER+total_LPC+total_LPE+total_PC+total_PE+total_SM, length(Lipids))

fracTable = corrTable %>% group_by(Gene) %>% mutate(Total = n()) %>% ungroup() %>%
  separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  group_by(Gene) %>% mutate(frac_TAG = sum(grepl('TAG', Class)/total_TAG),
                            frac_DAG = sum(Class == 'DAG')/total_DAG,
                            frac_CE = sum(Class == 'CE')/total_CE,
                            frac_CER = sum(Class == 'CER')/total_CER,
                            frac_FFA = sum(Class == 'FFA')/total_FFA,
                            frac_HCER = sum(Class == 'HCER')/total_HCER,
                            frac_LPC = sum(Class == 'LPC')/total_LPC,
                            frac_LPE = sum(Class == 'LPE')/total_LPE,
                            frac_PC = sum(Class == 'PC')/total_PC,
                            frac_PE = sum(Class == 'PE')/total_PE,
                            frac_SM = sum(Class == 'SM')/total_SM) %>% ungroup() %>%
  dplyr::select(-c(Lipid, Class, Bicor, Adj_P)) %>% distinct()
```

```{r}
# write as csv files
write.csv(corrTable, '~/Desktop/ETV007/processed_data/GENE-PLASMALIPID-corrTable_FDR<0.05.csv', row.names = FALSE, quote = FALSE)
write.csv(freqTable, '~/Desktop/ETV007/processed_data/GENE-PLASMALIPID-freqTable_FDR<0.05.csv', row.names = FALSE, quote = FALSE)
write.csv(fracTable, '~/Desktop/ETV007/processed_data/GENE-PLASMALIPID-fracTable_FDR<0.05.csv', row.names = FALSE, quote = FALSE)
```

# load in correlation/frequency/fraction tables =====================

```{r}
# load data from here from now on
corrTable = read.csv('~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-corrTable_FDR<0.05.csv', header = TRUE, stringsAsFactors = FALSE)
freqTable = read.csv('~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-freqTable_FDR<0.05.csv', header = TRUE, stringsAsFactors = FALSE)
fracTable = read.csv('~/Desktop/ETV007/processed_data/GENE-LIVERLIPID-fracTable_FDR<0.05.csv', header = TRUE, stringsAsFactors = FALSE)
```

```{r}
# LIVER 
# heatmap of the top 50 genes present in the most significant gene-lipid correlation pairs. Examining correlations for top 50 genes across all lipid species (top 50 TAG)

# obtain top 50 most abundant TAG species
TAG = ordered_liverData %>% tibble::rownames_to_column(var = "Mouse_ID") %>% gather(Lipid, Value, 2:ncol(.)) %>%
  filter(grepl("TAG", Lipid)) %>% group_by(Lipid) %>% mutate(Median = median(Value)) %>% ungroup() %>% dplyr::select(Lipid, Median) %>% distinct() %>% top_n(n=50, wt=Median) 

# extract remaining species that are not TAG
all_other_species = ordered_liverData %>% tibble::rownames_to_column(var = "Mouse_ID") %>% gather(Lipid, Value, 2:ncol(.)) %>% filter(!grepl("TAG", Lipid)) %>% dplyr::select(Lipid) %>% distinct()

# These are all the lipids we are going to include in the heatmap
lipid_list = append(TAG$Lipid, all_other_species$Lipid)

# take top 50 genes from all significant gene-lipid correlation pairs, ranked by adjusted P value
sig = corrTable %>% arrange(Adj_P) %>% dplyr::select(Gene) %>% distinct() %>% head(50)

# get the correlations for the heatmap
subset_gene_data = ordered_geneData %>% dplyr::select(all_of(sig$Gene))
subset_lipid_data = ordered_liverData %>% dplyr::select(all_of(lipid_list))
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

cluster_lipid_species_by_class <- function(corr_matrix) {
  result = data.frame("Lipid" = NULL, "LipidClass" = NULL, stringsAsFactors = FALSE)
  data = data.frame(t(corr$bicor), "Lipid" = row.names(t(corr$bicor))) %>%
    separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>% 
    dplyr::mutate("LipidClass" = ifelse(grepl("PE[.]O", Lipid), "PE_O",
                          ifelse(grepl("TAG", Class), "TAG",
                          ifelse(grepl("PE[.]P", Lipid), "PE_P", Class))))
  for(class in c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM")) {
    filtered_data = data %>% filter(LipidClass == class) %>% tibble::column_to_rownames(var = "Lipid")
    order = hclust(dist(filtered_data[,-c((ncol(filtered_data)-2):ncol(filtered_data))], method = "euclidean"), 
                   method = "median")$order
    ordered_data = data %>% filter(LipidClass == class) %>% arrange(factor(Lipid, levels = Lipid[order])) %>% 
      dplyr::select(Lipid, LipidClass)
    result = rbind(result, ordered_data)
  } 
  return(result)
}

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# create the annotations for the lipids
colors_lipidlist = data.frame("Lipid" = colnames(corr$bicor)) %>% separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>% mutate("LipidClass" = ifelse(grepl("PE[.]O", Lipid), "PE_O",
                                                 ifelse(grepl("TAG", Class), "TAG",
                                                 ifelse(grepl("PE[.]P", Lipid), "PE_P", Class)))) %>% 
  dplyr::select(-Class) %>% tibble::column_to_rownames(var = "Lipid") %>%
  left_join(., color_mapping, by = "LipidClass")

# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/test.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), fontsize = 22,
         cexRow = .9, scale = "none")
```

```{r}
# PLASMA 
# heatmap of the top 50 genes present in the most significant gene-lipid correlation pairs. Examining correlations for top 50 genes across all lipid species (top 50 TAG)

# obtain top 50 most abundant TAG species
TAG = ordered_plasmaData %>% tibble::rownames_to_column(var = "Mouse_ID") %>% gather(Lipid, Value, 2:ncol(.)) %>%
  filter(grepl("TAG", Lipid)) %>% group_by(Lipid) %>% mutate(Median = median(Value)) %>% ungroup() %>% dplyr::select(Lipid, Median) %>% distinct() %>% top_n(n=50, wt=Median) 

# extract remaining species that are not TAG
all_other_species = ordered_plasmaData %>% tibble::rownames_to_column(var = "Mouse_ID") %>% gather(Lipid, Value, 2:ncol(.)) %>% filter(!grepl("TAG", Lipid)) %>% dplyr::select(Lipid) %>% distinct()

# These are all the lipids we are going to include in the heatmap
lipid_list = append(TAG$Lipid, all_other_species$Lipid)

# take top 50 genes from all significant gene-lipid correlation pairs, ranked by adjusted P value
sig = corrTable %>% arrange(Adj_P) %>% dplyr::select(Gene) %>% distinct() %>% head(50)

# get the correlations for the heatmap
subset_gene_data = ordered_geneData2 %>% dplyr::select(all_of(sig$Gene))
subset_lipid_data = ordered_plasmaData %>% dplyr::select(all_of(lipid_list))
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

cluster_lipid_species_by_class <- function(corr_matrix) {
  result = data.frame("Lipid" = NULL, "LipidClass" = NULL, stringsAsFactors = FALSE)
  data = data.frame(t(corr$bicor), "Lipid" = row.names(t(corr$bicor))) %>%
    separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>% 
    dplyr::mutate("LipidClass" = ifelse(grepl("PE[.]O", Lipid), "PE_O",
                          ifelse(grepl("TAG", Class), "TAG",
                          ifelse(grepl("PE[.]P", Lipid), "PE_P", Class))))
  for(class in c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PC", "SM")) {
    filtered_data = data %>% filter(LipidClass == class) %>% tibble::column_to_rownames(var = "Lipid")
    order = hclust(dist(filtered_data[,-c((ncol(filtered_data)-2):ncol(filtered_data))], method = "euclidean"), 
                   method = "median")$order
    ordered_data = data %>% filter(LipidClass == class) %>% arrange(factor(Lipid, levels = Lipid[order])) %>% 
      dplyr::select(Lipid, LipidClass)
    result = rbind(result, ordered_data)
  } 
  return(result)
}

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# create the annotations for the lipids
colors_lipidlist = data.frame("Lipid" = colnames(corr$bicor)) %>% separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>% mutate("LipidClass" = ifelse(grepl("PE[.]O", Lipid), "PE_O",
                                                 ifelse(grepl("TAG", Class), "TAG",
                                                 ifelse(grepl("PE[.]P", Lipid), "PE_P", Class)))) %>% 
  dplyr::select(-Class) %>% tibble::column_to_rownames(var = "Lipid") %>%
  left_join(., color_mapping, by = "LipidClass")

# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = colors_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/plasma.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), labCol = NA, fontsize = 22,
         cexRow = .9, scale = "none")
```

### PATHWAY HEATMAPS ======================================

```{r}
library(KEGGREST)
library(org.Mm.eg.db)

# 02: Steroid biosynthesis pathway correlations
res = keggLink("mmu", "path:mmu00100")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/steroid_biosynthesis.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), 
        fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Steroid hormone biosynthesis pathway correlations
res = keggLink("mmu", "path:mmu00140")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/steroid_hormone_biosynthesis.pdf', height = 10, width = 24, verbose = TRUE, 
         color = rev(col), fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Terpenoid backbone biosynthesis pathway correlations
res = keggLink("mmu", "path:mmu00900")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/terpenoid_backbone_biosynthesis.pdf', height = 10, width = 24, verbose = TRUE, 
         color = rev(col), fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Bile secretion pathway correlations
res = keggLink("mmu", "path:mmu04976")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/bile_secretion.pdf', height = 15, width = 24, verbose = TRUE, color = rev(col), 
         fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Linoleic acid metabolism correlations
res = keggLink("mmu", "path:mmu00591")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/linoleic_acid_metabolism.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), 
         fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# PPAR signaling pathway correlations
res = keggLink("mmu", "path:mmu03320")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/PPAR_signaling_pathway.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), 
         fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Protein digestion and absorption correlations
res = keggLink("mmu", "path:mmu04974")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/protein_digestion_and_absorption.pdf', height = 10, width = 24, verbose = TRUE, 
         color = rev(col), fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Complement and coagulation cascades

res = keggLink("mmu", "path:mmu04610")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/complement_and_coagulation_cascades.pdf', height = 17, width = 24, verbose = TRUE, 
         color = rev(col), fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# Fatty acid metabolism

res = keggLink("mmu", "path:mmu01212")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/fatty_acid_metabolism.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), 
         fontsize = 22, cexRow = .9, scale = "none")
```

```{r}
# TNF signaling pathway

res = keggLink("mmu", "path:mmu04668")
my.symbols <- gsub('mmu:', '', res)

genes = select(org.Mm.eg.db, 
       keys = my.symbols,
       columns = c("ENTREZID", "SYMBOL"),
       keytype = "ENTREZID")

subset_gene_data = ordered_geneData %>% dplyr::select(one_of(genes$SYMBOL))
# get subset_liver_data from above
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# cluster the lipids within their respective classes 
ann_colors <- c("#FFFFE0", "#5757F9", "#A00000", "#00C000", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#C5944E", "#034E61", "#FFA040", "#077E97", "#606060")
color_mapping = data.frame("LipidClass" = c("TAG", "DAG", "CE", "CER", "FFA", "HCER", "LPC", "LPE", "PE", "PE_O", "PE_P", "PC", "SM"), "Color" = ann_colors, stringsAsFactors = FALSE)

# ordering of the lipid columns
ordered_lipidlist = cluster_lipid_species_by_class(corr$bicor) %>% tibble::column_to_rownames(var = "Lipid")
  
# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "RdBu"))(100)

# plot heatmap
data = t(corr$bicor)[rownames(ordered_lipidlist),]
aheatmap(t(data), annCol = ordered_lipidlist$LipidClass, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = NA,
         filename = '~/Desktop/pathways/TNF_signaling_pathway.pdf', height = 10, width = 24, verbose = TRUE, color = rev(col), 
         fontsize = 22, cexRow = .9, scale = "none")
```













```{r}
# heatmap of complement gene correlations with lipid

# obtain top 50 most abundant TAG species
TAG = ordered_liverData %>% tibble::rownames_to_column(var = "Mouse_ID") %>% gather(Lipid, Value, 2:ncol(.)) %>%
  filter(grepl("TAG", Lipid)) %>% group_by(Lipid) %>% mutate(Median = median(Value)) %>% ungroup() %>% dplyr::select(Lipid, Median) %>% distinct() %>% top_n(n=50, wt=Median) 

# extract remaining species that are not TAG
all_other_species = ordered_liverData %>% tibble::rownames_to_column(var = "Mouse_ID") %>% gather(Lipid, Value, 2:ncol(.)) %>% filter(!grepl("TAG", Lipid)) %>% dplyr::select(Lipid) %>% distinct()

# These are all the lipids we are going to include in the heatmap
lipid_list = append(TAG$Lipid, all_other_species$Lipid)

# take all complement genes
key = read.table('~/Desktop/ETV007/raw_data/ensembl84_info.txt', header = TRUE, sep = '\t', quote="", fill=FALSE, stringsAsFactors = FALSE)
mapping = key %>% dplyr::select(Ensembl.Gene.ID, Associated.Gene.Name, Description) %>% distinct()
complement = mapping %>% filter(grepl("complement ", mapping$Description))

# get the correlations for the heatmap
subset_gene_data = ordered_geneData %>% dplyr::select(starts_with(complement$Associated.Gene.Name) & ends_with(complement$Associated.Gene.Name))
subset_lipid_data = ordered_liverData %>% dplyr::select(all_of(lipid_list))
corr = bicorAndPvalue(subset_gene_data, subset_lipid_data)
subset_corrTable = createCorrTable(corr, 1)

# create the annotations for the lipids
ordered_lipidlist = data.frame("Lipid" = colnames(corr$bicor)) %>% separate(col = 'Lipid', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>% mutate("LipidClass" = ifelse(grepl("TAG", Class), "TAG", Class)) %>% dplyr::select(-Class) %>% tibble::column_to_rownames(var = "Lipid")

# color palette for heatmap
col <- colorRampPalette(brewer.pal(9, "Spectral"))(100)

# plot heatmap
aheatmap(corr$bicor, annCol = ordered_lipidlist, distfun = 'euclidean', hclustfun = 'median', Rowv = FALSE, Colv = FALSE,
         filename = '~/Desktop/complement.pdf', height = 10, width = 16, verbose = TRUE, color = col, labCol = NA, fontsize = 22,
         cexRow = .9)
```

```{r}
# load in liver lipid data
raw_liverData = read.csv('~/Desktop/ETV007/raw_data/ETV007_Liver_Lipidomics.csv', header = TRUE, fill = TRUE, stringsAsFactors = FALSE)
complete_liverData = raw_liverData[ ,colSums(is.na(raw_liverData)) <= 0*nrow(raw_liverData)] # remove any column with NA
row.names(complete_liverData) = paste(complete_liverData$Treatment, "_", complete_liverData$Mouse_ID, sep = "")
`%notin%` <- Negate(`%in%`)
filtered_liverData = filter(complete_liverData, Mouse_ID %notin% c(53,39)) # check lipidomics script for outlier detection
row.names(filtered_liverData) = paste(filtered_liverData$Treatment, "_", filtered_liverData$Mouse_ID, sep = "")
filtered_liverData = filtered_liverData %>% dplyr::select(-c(Mouse_ID, Treatment))
```

```{r}
# load in plasma lipid data
raw_plasmaData <- read.csv("~/Desktop/ETV007/raw_data/ETV007_Plasma_Lipidomics.csv", header = TRUE, fill = TRUE, stringsAsFactors = FALSE)
complete_plasmaData = raw_plasmaData[ ,colSums(is.na(raw_plasmaData)) <= 0*nrow(raw_plasmaData)] # remove any column with NA
mouse_to_diet_ID = complete_liverData[,c(1,2)]
complete_plasmaData = complete_plasmaData %>% left_join(., mouse_to_diet_ID, by = c("Name" = "Mouse_ID"))
row.names(complete_plasmaData) = paste(complete_plasmaData$Treatment, "_", complete_plasmaData$Name, sep = "")
complete_plasmaData = complete_plasmaData %>% select(-Name)
```





