---
title: "Lipidomics analysis"
author: "Timothy Yu"
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggfortify)
library(bnstruct)
library(viridis)
library(DescTools)
library(RColorBrewer)
require(cowplot)
theme_set(theme_cowplot())
source('utils/utils.R')
```

Liver lipidomics 
```{r}
liverData = read.csv('../processed_data/datasets/Lipidomics_liver_normliverweight.csv', header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
```

```{r}
autoplot(prcomp((liverData[-c(1,2)] %>% select_if(~ !any(is.na(.)))), scale. = TRUE), 
         data = liverData, colour = 'Treatment', 
         size = 0.1, label = TRUE, label.size = 3, frame = TRUE, frame.type = 'norm', 
         frame.level = 0.90) + 
         scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41')) +
         scale_fill_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))
# By 90% confidence ellipse, Mice 53 and 39 are outliers. We will remove them and re-plot the PCA. They are also excluded from the remaining analysis.
```

```{r}
# PCA plot of liver lipidomics data
liverData = liverData %>% filter(!ID %in% c(39,53))
autoplot(prcomp((liverData[-c(1,2)] %>% select_if(~ !any(is.na(.)))), scale. = TRUE), 
         data = liverData, colour = 'Treatment', size = 2.5) + 
  scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))
ggsave('../figures/lipidomics_liver_pca.pdf', height = 3.5, width = 5)
```
```{r}
# make bubble plot
colors <- c("#A00000", "#00C000", "#5757F9", "#FF6000", "#0000C0", "#C0C000", "#D7B0B0",
            "#9F044D", "#077E97", "#C5944E", "#034E61", "#FFA040", "#606060", "#fcfc81")

bubdata = makeBubbleData(liverData)
bubp = getBubbleSignificance(bubdata)
makeBubblePlot(bubp, abundance=FALSE, colors=colors, bubble_range=c(3,10))
ggsave('../figures/lipidomics_liver_bubble_plot.pdf', height = 5.5, width = 15)
write.csv(bubp, '../processed_data/misc/lipidomics_liver_bubble_stats.csv')
```

```{r}
# triglyceride abundance heat map for a specific TG class (TG48)
scaled_liverData = cbind(liverData[,c(1,2)], scale(liverData[,-c(1,2)])) # mean 0, sd 1

TG48_data = scaled_liverData %>%
  select_if(~ !any(is.na(.))) %>%
  gather(Feature, Value, 3:ncol(.)) %>%
  separate(col = 'Feature', into = c("Class", "Chain"), sep = "\\.", 
          remove = FALSE, extra = 'drop') %>%
  filter(Class == 'TG', Chain == 48)

order = c(unique((TG48_data %>% filter(Treatment == 'Chow8'))$ID),
          unique((TG48_data %>% filter(Treatment == 'WD2'))$ID),
          unique((TG48_data %>% filter(Treatment == 'WD4'))$ID),
          unique((TG48_data %>% filter(Treatment == 'WD6'))$ID),
          unique((TG48_data %>% filter(Treatment == 'WD8'))$ID))

TG48_data %>%
  ggplot(aes(x = Feature, y = as.factor(ID))) + 
  geom_tile(aes(fill = Value), alpha = 1, color = 'black', size = 0.1) + 
  scale_fill_gradient2(low = "#0000FF", mid = "#FFFFFF", high ="#FF0000", midpoint=0) + 
  scale_y_discrete(limits = rev(factor(order))) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        axis.title.x = element_blank(), axis.title.y = element_blank())
ggsave('../figures/lipidomics_liver_TG48_normliverweight_heatmap.pdf', height = 14, width = 9)
```

Plasma lipidomics 
```{r}
plasmaData = read.csv('../processed_data/datasets/Lipidomics_plasma.csv', header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
```

```{r}
autoplot(prcomp((plasmaData[-c(1,2)] %>% select_if(~ !any(is.na(.)))), scale. = TRUE), 
         data = plasmaData, colour = 'Treatment', 
         size = 0.1, label = TRUE, label.size = 3, frame = TRUE, frame.type = 'norm', 
         frame.level = 0.95) + 
         scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41')) +
         scale_fill_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))
```
```{r}
# PCA plot of plasma lipidomics data
autoplot(prcomp((plasmaData[-c(1,2)] %>% select_if(~ !any(is.na(.)))), scale. = TRUE), data = plasmaData, colour = 'Treatment', size = 2.5) + scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))
ggsave('../figures/lipidomics_plasma_pca.pdf', height = 3.5, width = 5)
```
```{r}
# make bubble plot
colors <- c("#A00000", "#00C000", "#5757F9", "#FF6000", "#0000C0", "#C0C000", "#D7B0B0",
            "#9F044D", "#077E97", "#606060", "#fcfc81")

bubdata = makeBubbleData(plasmaData) %>% filter(!Feat %in% c("PE", "PE_O", "PE_P"))
bubp = getBubbleSignificance(bubdata)
makeBubblePlot(bubp, abundance=FALSE, colors=colors, bubble_range=c(3,10))
ggsave('../figures/lipidomics_plasma_bubble_plot.pdf', height = 5, width = 15)
write.csv(bubp, '../processed_data/misc/lipidomics_plasma_bubble_stats.csv')
```

```{r}
# CE abundance heat map for a specific CE (CE(18:1))
abundant_CE = plasmaData %>% select(grep("CE", colnames(.))) %>%
  colMeans() %>% as.data.frame() %>%
  filter(. > 50)

scaled_plasmaData = cbind(plasmaData[,c(1,2)], 
                    scale(plasmaData %>% select(rownames(abundant_CE)))) # mean 0, sd 1

CE_data = scaled_plasmaData %>%
  gather(Feature, Value, 3:ncol(.))

order = c(unique((CE_data %>% filter(Treatment == 'Chow8'))$ID),
          unique((CE_data %>% filter(Treatment == 'WD2'))$ID),
          unique((CE_data %>% filter(Treatment == 'WD4'))$ID),
          unique((CE_data %>% filter(Treatment == 'WD6'))$ID),
          unique((CE_data %>% filter(Treatment == 'WD8'))$ID))

CE_data %>% ggplot(aes(x = Feature, y = as.factor(ID))) + 
  geom_tile(aes(fill = Value), alpha = 1, color = 'black', size = 0.1) + 
  scale_fill_gradient2(low = "#0000FF", mid = "#FFFFFF", high ="#FF0000", midpoint=0) + 
  scale_y_discrete(limits = rev(factor(order))) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        axis.title.x = element_blank(), axis.title.y = element_blank())
ggsave('../figures/lipidomics_plasma_CE_heatmap.pdf', height = 14, width = 9)
```
```{r}
# corresponding plot for plasma -- triglyceride abundance heat map for a specific TG class (TG48)
scaled_plasmaData = cbind(plasmaData[,c(1,2)], scale(plasmaData[,-c(1,2)])) # mean 0, sd 1

plasma_TG48_data = scaled_plasmaData %>%
  select_if(~ !any(is.na(.))) %>%
  gather(Feature, Value, 3:ncol(.)) %>%
  separate(col = 'Feature', into = c("Class", "Chain"), sep = "\\.", 
          remove = FALSE, extra = 'drop') %>%
  filter(Class == 'TG', Chain == 48) %>%
  filter(!ID %in% c(55,56)) # 2 outliers

order = c(unique((plasma_TG48_data %>% filter(Treatment == 'Chow8'))$ID),
          unique((plasma_TG48_data %>% filter(Treatment == 'WD2'))$ID),
          unique((plasma_TG48_data %>% filter(Treatment == 'WD4'))$ID),
          unique((plasma_TG48_data %>% filter(Treatment == 'WD6'))$ID),
          unique((plasma_TG48_data %>% filter(Treatment == 'WD8'))$ID))

plasma_TG48_data %>%
  ggplot(aes(x = Feature, y = as.factor(ID))) + 
  geom_tile(aes(fill = Value), alpha = 1, color = 'black', size = 0.1) + 
  scale_fill_gradient2(low = "#0000FF", mid = "#FFFFFF", high ="#FF0000", midpoint=0) + 
  scale_y_discrete(limits = rev(factor(order))) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
        axis.title.x = element_blank(), axis.title.y = element_blank())
ggsave('../figures/lipidomics_plasma_TG48_heatmap.pdf', height = 14, width = 9)
```

```{r}
# correlate total lipid classes between liver and plasma
totalLipidbyClass_liver = liverData %>%
  gather(Feature, Value, 3:ncol(.)) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  mutate(RefinedClass = ifelse(grepl("PE[.]O", Feature), "PE_O",
                        ifelse(grepl("PE[.]P", Feature), "PE_P", Class))) %>%
  select(-Class) %>%
  group_by(ID, RefinedClass) %>%
  drop_na() %>%
  mutate(totalLipid = sum(Value)) %>%
  ungroup() %>%
  select(ID, Treatment, RefinedClass, totalLipid) %>%
  distinct() %>%
  group_by(RefinedClass) %>%
  mutate(n_groups = length(unique(Treatment))) %>%
  filter(n_groups == 5) %>%
  ungroup() %>%
  select(-n_groups)

totalLipidbyClass_plasma = plasmaData %>%
  gather(Feature, Value, 3:ncol(.)) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  mutate(RefinedClass = ifelse(grepl("PE[.]O", Feature), "PE_O",
                        ifelse(grepl("PE[.]P", Feature), "PE_P", Class))) %>%
  select(-Class) %>%
  group_by(ID, RefinedClass) %>%
  drop_na() %>%
  mutate(totalLipid = sum(Value)) %>%
  ungroup() %>%
  select(ID, Treatment, RefinedClass, totalLipid) %>%
  distinct() %>%
  group_by(RefinedClass) %>%
  mutate(n_groups = length(unique(Treatment))) %>%
  filter(n_groups == 5) %>%
  ungroup() %>%
  select(-n_groups)
 
lipids_in_common = intersect(totalLipidbyClass_liver$RefinedClass, totalLipidbyClass_plasma$RefinedClass)
 
df = data.frame("LipidClass" = character(), "Spearman_corr" = numeric(), "p_val" = numeric())
for (lipid1 in lipids_in_common) {
  lipid_in_liver = totalLipidbyClass_liver %>% filter(RefinedClass == lipid1)
  for (lipid2 in lipids_in_common) {
    lipid_in_plasma = totalLipidbyClass_plasma %>% filter(RefinedClass == lipid2)
    combined = left_join(lipid_in_liver, lipid_in_plasma, by = 'ID')
    corr = cor.test(combined$totalLipid.x, 
                    combined$totalLipid.y, 
                    method=c("pearson", "kendall", "spearman"))$estimate
    p = cor.test(combined$totalLipid.x, 
                 combined$totalLipid.y, 
                 method=c("pearson", "kendall", "spearman"))$p.value
    df = rbind(df, data.frame("Lipid_liver" = lipid1,
                              "Lipid_plasma" = lipid2,
                              "Spearman_corr" = corr,
                              "p_val" = p))
  }
}

# save dataframe
write.csv(df, '../processed_data/misc/liver_plasma_lipid_class_pairwise_corr.csv', row.names=FALSE)

df %>%
  ggplot(aes(x=Lipid_liver, y=Lipid_plasma)) +
  geom_tile(aes(fill=Spearman_corr), alpha=1, color='black', size=0.1) +
  scale_fill_gradient2(low = "#0000FF", mid = "#FFFFFF", high ="#FF0000", midpoint=0) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ggsave('../figures/lipidomics_plasma_liver_total_corr_heatmap.pdf', height = 4, width = 6)
```
























```{r}
left_join(totalLipidbyClass_liver, totalLipidbyClass_plasma, by=c("ID","RefinedClass", "Treatment")) %>%
  ggplot(aes(x=totalLipid.x, y=totalLipid.y)) +
  geom_point() +
  facet_wrap(~RefinedClass, scales='free')
```
```{r}
colors <- c("#A00000", "#00C000", "#5757F9", "#FF6000", "#0000C0", "#C0C000", "#D7B0B0", "#9F044D", 
            "#077E97", "#606060", "#fcfc81")

df %>% ggplot(aes(x = LipidClass, y = Spearman_corr)) + 
  geom_bar(stat = 'identity', aes(fill=LipidClass), color = 'black', size=0.5) +
  scale_fill_manual(values = colors) +
  geom_hline(yintercept=1, color='maroon', linetype='dashed') +
  geom_hline(yintercept=-1, color='maroon', linetype='dashed') +
  labs(y = 'Spearman correlation', x = 'Total lipid by class') +
  theme(legend.position = "None")
```

```{r}
# load in data
raw_liverData = read.csv('../raw_data/ETV007_Liver_Lipidomics.csv', header = TRUE, fill = TRUE, stringsAsFactors = FALSE)
raw_plasmaData <- read.csv("../raw_data/ETV007_Plasma_Lipidomics.csv", header = TRUE, fill = TRUE, stringsAsFactors = FALSE)
```

```{r}
# PCA plot for liver lipids by diet
# looks like, by 95% confidence ellipse, Mice 53 and 39 are outliers. We remove them and replot the PCA. They are also excluded from the remaining analysis.
complete_liverData = raw_liverData[ ,colSums(is.na(raw_liverData)) <= 0*nrow(raw_liverData)] # remove any column with NA
row.names(complete_liverData) = paste(complete_liverData$Treatment, "_", complete_liverData$Mouse_ID)
autoplot(prcomp(complete_liverData[-c(1,2)], scale. = TRUE), data = complete_liverData, colour = 'Treatment', label = TRUE, label.size = 3, frame = TRUE, frame.type = 'norm', frame.level = 0.95)

`%notin%` <- Negate(`%in%`)
filtered_liverData = filter(complete_liverData, Mouse_ID %notin% c(53,39))
row.names(filtered_liverData) = paste(filtered_liverData$Treatment, "_", filtered_liverData$Mouse_ID, sep = "")
write.csv(filtered_liverData %>% select(-c(Mouse_ID, Treatment)), '../processed_data/data_tables/lipidomics_liver_clean.csv')

autoplot(prcomp(filtered_liverData[-c(1,2)], scale. = TRUE), data = filtered_liverData, colour = 'Treatment', size = 2.5) + scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))
ggsave('../figures/lipidomics_liver_pca.pdf', height = 4, width = 6)
```


```{r}
# PCA plot for plasma lipids by diet
# looks like, by 95% confidence ellipse, no outliers

complete_plasmaData = raw_plasmaData[ ,colSums(is.na(raw_plasmaData)) <= 0*nrow(raw_plasmaData)] # remove any column with NA
mouse_to_diet_ID = complete_liverData[,c(1,2)]
complete_plasmaData = complete_plasmaData %>% left_join(., mouse_to_diet_ID, by = c("Name" = "Mouse_ID"))
row.names(complete_plasmaData) = paste(complete_plasmaData$Treatment, "_", complete_plasmaData$Name, sep = "")
complete_plasmaData = complete_plasmaData %>% select(-Name)
write.csv(complete_plasmaData %>% select(-Treatment), '../processed_data/data_tables/lipidomics_plasma_clean.csv')

autoplot(prcomp(complete_plasmaData[,-ncol(complete_plasmaData)], scale. = TRUE), data = complete_plasmaData, colour = 'Treatment', label = TRUE, label.size = 3, frame = TRUE, frame.type = 'norm', frame.level = 0.95)
autoplot(prcomp(complete_plasmaData[,-ncol(complete_plasmaData)], scale. = TRUE), data = complete_plasmaData, colour = 'Treatment', size = 2.5) + scale_color_manual(values = c('black', '#3b9bb3', '#75af4f', '#e39225', '#c13b41'))
ggsave('../figures/lipidomics_plasma_pca.pdf', height = 4, width = 6)
```

```{r}
# Boxplots of liver lipid class changes with respect to diet
liverData %>%
  gather(Feature, Value, 3:ncol(.)) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  mutate(RealClass = ifelse(grepl('TAG', Class), 'TAG',
                     ifelse(grepl("PE[.]O", Feature), "PE_O",
                     ifelse(grepl("PE[.]P", Feature), "PE_P", Class)))) %>%
  dplyr::select(-Class) %>%
  group_by(ID, RealClass) %>%
  mutate(sumLipids = sum(Value)) %>%
  ungroup() %>%
  dplyr::select(ID, Treatment, RealClass, sumLipids) %>%
  distinct() %>%
  ggplot(aes(x = Treatment, y = sumLipids)) +
  geom_boxplot(aes(fill = Treatment), outlier.shape = NA, alpha = 0.6) + geom_jitter(aes(fill = Treatment), pch = 21, color = 'black', size = 2) + 
  scale_fill_viridis(discrete = TRUE) +
  facet_wrap(~RealClass, scales = 'free') +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        legend.position = 'none') +
  labs(title = 'Lipid Classes in Liver', y = 'Total Lipid Amount', x = 'Diet Treatment')
ggsave('../figures/lipidomics_liver_boxplots_by_class.pdf', height = 9, width = 11)
```

```{r}
# Boxplots of plasma lipid class changes with respect to diet
complete_plasmaData %>%
  tibble::rownames_to_column(var = "Mouse_ID") %>%
  gather(Feature, Value, 2:275) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  mutate(RealClass = ifelse(grepl('TAG', Class), 'TAG',
                     ifelse(grepl("PE[.]O", Feature), "PE_O",
                     ifelse(grepl("PE[.]P", Feature), "PE_P", Class)))) %>%
  dplyr::select(-Class) %>%
  group_by(Mouse_ID, RealClass) %>%
  mutate(sumLipids = sum(Value)) %>%
  ungroup() %>%
  dplyr::select(Mouse_ID, Treatment, RealClass, sumLipids) %>%
  distinct() %>%
  ggplot(aes(x = Treatment, y = sumLipids)) +
  geom_boxplot(aes(fill = Treatment), outlier.shape = NA, alpha = 0.6) + geom_jitter(aes(fill = Treatment), pch = 21, color = 'black', size = 2) + 
  scale_fill_viridis(discrete = TRUE) +
  facet_wrap(~RealClass, scales = 'free') +
  theme(axis.text.x = element_text(angle=45, hjust=1),
        legend.position = 'none') +
  labs(title = 'Plasma Classes in Liver', y = 'Total Lipid Amount', x = 'Diet Treatment')
ggsave('../figures/lipidomics_plasma_boxplots_by_class.pdf', height = 9, width = 11)
```

```{r}
# Obtain liver data bubble plot data
totalLipid = filtered_liverData %>%
  gather(Feature, Value, 3:578) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  mutate(RealClass = ifelse(grepl('TAG', Class), 'TAG',
                     ifelse(grepl("PE[.]O", Feature), "PE_O",
                     ifelse(grepl("PE[.]P", Feature), "PE_P", Class)))) %>%
  dplyr::select(-Class) %>%
  group_by(Mouse_ID, RealClass) %>%
  mutate(sumLipids = sum(Value)) %>%
  ungroup() %>%
  dplyr::select(Mouse_ID, Treatment, RealClass, sumLipids) %>%
  distinct()

# Use Dunnett test to get significance for each lipid class for WD2, WD4, WD6, WD8 compared to control (CHOW8).
totalLipid$Treatment <- as.factor(totalLipid$Treatment)
lipidClasses = levels(factor(totalLipid$RealClass))
liver_table = data.frame("Comparison" = character(), "pval" = double(), "Median" = double(), "FC" = double(), "RealClass" = character(), stringsAsFactors = FALSE)

for(i in lipidClasses) {
  result = DunnettTest(sumLipids ~ Treatment, data = filter(totalLipid, RealClass == i), control = 'CHOW8')
  FC = totalLipid %>% filter(RealClass == i) %>% group_by(Treatment) %>% mutate(Median = median(sumLipids)) %>% ungroup() %>%
    dplyr::select(Treatment, RealClass, Median) %>% distinct() %>% mutate(FC = Median/filter(., Treatment == 'CHOW8')$Median) %>%
    filter(Treatment != 'CHOW8') %>% mutate(Comparison = paste(Treatment, "-", "CHOW8", sep = "")) %>% select(Comparison, Median, FC, RealClass)
  # combine the significance and fold-change into single entry
  entry = as.data.frame(result$CHOW8) %>% select(pval) %>% tibble::rownames_to_column(var = "Comparison") %>% left_join(., FC, by = "Comparison")
  liver_table = rbind(liver_table, entry)
}
```

```{r}
# Figure 3C: Liver bubble graph of diet vs. fold-change. Size highlights significance.
ann_colors <- c("#A00000", "#00C000", "#5757F9", "#FF6000", "#0000C0", "#D7B0B0", "#9F044D", "#077E97", "#C5944E", "#034E61", "#FFA040", "#606060", "#FFFFE0")
liver_table %>%
  mutate(log2FC = log2(FC)) %>%
  mutate(log10P = -log10(pval)) %>%
  mutate(log10Abundance = log10(Median)) %>%
  arrange(desc(log10Abundance)) %>%
  mutate(Significant = ifelse(pval < 0.05, "yes", "no")) %>%
  ggplot(aes(x=log2FC, y=log10Abundance, size=log10P, fill=RealClass)) +
    geom_vline(xintercept = 0, linetype = 'solid', color = 'black') +
    geom_hline(yintercept = c(2, 3, 4, 5, 6), linetype = 'dotted', color = 'grey70', size = 1) +
    geom_point(alpha=0.9, aes(fill = RealClass), color = 'black', pch = 21, stroke = 1) +
    scale_size(range = c(5, 20), name="Significance -log10(P)") +
    xlim(-2, 6) +
    scale_fill_manual(values = ann_colors) +
    facet_grid(~Comparison, scales = 'fixed') +
    labs(x = "log2(Fold-change)", y = "log10(Abundance)")
ggsave('../figures/lipidomics_liver_bubble_plot.pdf', height = 5, width = 18)
```

```{r}
# Obtain plasma data bubble plot data
totalLipid = complete_plasmaData %>%
  tibble::rownames_to_column(var = "Mouse_ID") %>%
  gather(Feature, Value, 2:275) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  mutate(RealClass = ifelse(grepl('TAG', Class), 'TAG', Class)) %>%
  dplyr::select(-Class) %>%
  group_by(Mouse_ID, RealClass) %>%
  mutate(sumLipids = sum(Value)) %>%
  ungroup() %>%
  dplyr::select(Mouse_ID, Treatment, RealClass, sumLipids) %>%
  distinct() 

# Use Dunnett test to get significance for each lipid class for WD2, WD4, WD6, WD8 compared to control (CHOW8).
totalLipid$Treatment <- as.factor(totalLipid$Treatment)
lipidClasses = levels(factor(totalLipid$RealClass))
plasma_table = data.frame("Comparison" = character(), "pval" = double(), "Median" = double(), "FC" = double(), "RealClass" = character(), stringsAsFactors = FALSE)

for(i in lipidClasses) {
  result = DunnettTest(sumLipids ~ Treatment, data = filter(totalLipid, RealClass == i), control = 'CHOW8')
  FC = totalLipid %>% filter(RealClass == i) %>% group_by(Treatment) %>% mutate(Median = median(sumLipids)) %>% ungroup() %>%
    dplyr::select(Treatment, RealClass, Median) %>% distinct() %>% mutate(FC = Median/filter(., Treatment == 'CHOW8')$Median) %>%
    filter(Treatment != 'CHOW8') %>% mutate(Comparison = paste(Treatment, "-", "CHOW8", sep = "")) %>% select(Comparison, Median, FC, RealClass)
  # combine the significance and fold-change into single entry
  entry = as.data.frame(result$CHOW8) %>% select(pval) %>% tibble::rownames_to_column(var = "Comparison") %>% left_join(., FC, by = "Comparison")
  plasma_table = rbind(plasma_table, entry)
}

plasma_sig = plasma_table %>% filter(pval > 0.05, RealClass %notin% c("HCER", "LPE", "CER"))
```

```{r}
# Plasma bubble graph of diet vs. fold-change. Size highlights significance.
ann_colors <- c("#A00000", "#5757F9", "#FF6000", "#D7B0B0", "#077E97", "#606060", "#FFFFE0")
plasma_table %>%
  filter(RealClass %notin% c("HCER", "LPE", "CER")) %>%
  mutate(log2FC = log2(FC)) %>%
  mutate(log10P = -log10(pval)) %>%
  mutate(log10Abundance = log10(Median)) %>%
  arrange(desc(log10Abundance)) %>%
  ggplot(aes(x=log2FC, y=log10Abundance, size=log10P, fill=RealClass)) +
    geom_vline(xintercept = 0, linetype = 'solid', color = 'black') +
    geom_hline(yintercept = c(2, 3, 4), linetype = 'dotted', color = 'grey70', size = 1) +
    geom_point(alpha=0.9, aes(fill = RealClass), color = 'black', pch = 21, stroke = 1) +
    scale_size(range = c(5, 20), name="Significance -log10(P)") +
    scale_fill_manual(values = ann_colors) +
    xlim(-1.5, 2) +
    facet_grid(~Comparison, scales = 'fixed') +
    labs(x = "log2(Fold-change)", y = "log10(Abundance)")
ggsave('../figures/lipidomics_plasma_bubble_plot.pdf', height = 5, width = 18)
```

```{r}
# triglyceride abundance heatmaps by TG class
scaled_liverData = cbind(filtered_liverData[,c(1,2)], scale(filtered_liverData[,-c(1,2)])) # mean 0, sd 1
TG_data = scaled_liverData %>%
  gather(Feature, Value, 3:578) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  filter(grepl("TAG", Class)) %>%
  group_by(Class, Mouse_ID) %>%
  mutate(summedLipid = sum(Value)) %>%
  ungroup() %>%
  select(Mouse_ID, Treatment, Class, summedLipid) %>%
  distinct()

order = c(1, 2, 3, 4, 9, 10, 11, 12, 17, 18, 19, 20, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 5, 6, 7, 8, 13, 14, 15, 16, 21, 22, 23, 24)
```

```{r}
# triglyceride heatmaps for specific class
TG48_data = scaled_liverData %>%
  gather(Feature, Value, 3:578) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  filter(grepl("TAG48", Class))

TG48_data %>% ggplot(aes(x = Feature, y = as.factor(Mouse_ID))) + geom_tile(aes(fill = Value), alpha = 1, color = 'white', size = 0.1) + scale_fill_distiller(palette = "Spectral") + scale_y_discrete(limits = rev(factor(order))) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), axis.title.x = element_blank(), axis.title.y = element_blank())

ggsave('../figures/lipidomics_liver_TG48_heatmap.pdf', height = 14, width = 9)
```

```{r}
# plasma CE heatmap
complete_plasmaData %>%
  tibble::rownames_to_column(var = "Mouse_ID") %>%
  gather(Feature, Value, 2:275) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  mutate(RealClass = ifelse(grepl('TAG', Class), 'TAG',
                     ifelse(grepl("PE[.]O", Feature), "PE_O",
                     ifelse(grepl("PE[.]P", Feature), "PE_P", Class)))) %>%
  dplyr::select(-Class) %>%
  group_by(Mouse_ID, RealClass) %>%
  mutate(sumLipids = sum(Value)) %>%
  ungroup() %>%
  dplyr::select(Mouse_ID, Treatment, RealClass, Feature, Value, sumLipids) %>%
  distinct() %>%
  #filter(RealClass == 'CE') %>%
  filter(Feature == 'CE.18.1.') %>%
  ggplot(aes(x = Treatment, y = Value)) + geom_boxplot() + geom_text(aes(label = Mouse_ID))

scaled_plasma = complete_plasmaData %>% dplyr::select(-Treatment) %>% tibble::rownames_to_column(var = "ID") %>% separate(col = "ID", into = c("Treatment", "Mouse_ID"), sep = "_", remove = TRUE)
scaled_plasma = cbind(scaled_plasma[,c(1,2)], scale(scaled_plasma[,-c(1,2)]))

plasmaCE_data = scaled_plasma %>%
  gather(Feature, Value, 3:276) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  na.omit() %>%
  filter(Class == "CE")

# remove outliers: Mouse 7, 23, 39, 44
order = c(1, 2, 3, 4, 9, 10, 11, 12, 17, 18, 19, 20, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 37, 38, 40, 41, 42, 43, 45, 46, 47, 48, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 5, 6, 8, 13, 14, 15, 16, 21, 22, 24)

plasmaCE_data %>% 
  filter(Mouse_ID %notin% c(7,23,39,44)) %>% 
  ggplot(aes(x = Feature, y = as.factor(Mouse_ID))) + geom_tile(aes(fill = Value), alpha = 1, color = 'white', size = 0.1) + scale_fill_distiller(palette = "Spectral") + scale_y_discrete(limits = rev(factor(order))) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), axis.title.x = element_blank(), axis.title.y = element_blank())

ggsave('../figures/lipidomics_plasma_CE_heatmap_1.pdf', height = 12, width = 9)
```






























```{r}
# Use k-means clustering to cluster individual lipid species 

# this data frame maps each individual lipid to its class
mapping = complete_liverData %>%
  gather(Feature, Value, 3:578) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  mutate(RealClass = ifelse(grepl('TAG', Class), 'TAG', Class)) %>%
  dplyr::select(Feature, RealClass) %>% distinct()
  
# Create the input files for k-means. I scale the data to standardize all individual lipids 
input = mutate_all(as.data.frame(t(scale(filter(complete_liverData, Mouse_ID %notin% c(53,39,48,13))[,-c(1:2)]))), function(x)
  as.numeric(as.character(x))) 
row.names(input) = row.names(as.data.frame(t(filter(complete_liverData, Mouse_ID %notin% c(53,39,48,13)))[-c(1:2),]))

inputWithMapping = input %>% as.data.frame() %>% tibble::rownames_to_column(var = "Feature") %>% left_join(., mapping, by = 'Feature')

# I specified 5 clusters because that seemed to separate the data best
set.seed(999)
kmeans_object = kmeans(input, 5)
autoplot(kmeans_object, data = inputWithMapping, frame = TRUE, size = 3, alpha = 0.7) + ggtitle("k-means clustering") + 
  scale_color_manual(values = c("#d843a9", "#3b1776", "#549ac1", "#f2cc5a", "#DC143C")) +
  scale_fill_manual(values = c("#d843a9", "#3b1776", "#549ac1", "#f2cc5a", "#DC143C"))

# Isolate the clusters
clusters = data.frame("Cluster" = kmeans_object$cluster) %>% tibble::rownames_to_column(var = "Feature")
```

```{r}
complete_liverData %>% gather(Feature, Value, 3:578) %>%
  left_join(., clusters, by = 'Feature') %>% group_by(Feature, Treatment) %>%
  mutate(Avg = mean(Value)) %>% ungroup() %>%
  select(Treatment, Feature, Avg, Cluster) %>% distinct() %>%
  ggplot(aes(x = Treatment, y = reorder(Feature, Cluster))) + geom_tile(aes(fill = log10(Avg))) +
  scale_fill_viridis()



  
  

  
  

cluster1 = filter(clusters, Cluster == 1)







```

```{r}
# Figure 2D: Volcano plot showing how lipids change over time

CHOW8 = filter(complete_liverData, Treatment == 'CHOW8') %>% gather(Feature, Value, 3:578) %>% group_by(Feature) %>% drop_na() %>% mutate(CHOW8_Avg = mean(Value)) %>% ungroup %>% select(Feature, CHOW8_Avg) %>% distinct()
WD2 = filter(complete_liverData, Treatment == 'WD2') %>% gather(Feature, Value, 3:578) %>% group_by(Feature) %>% drop_na() %>% mutate(WD2_Avg = mean(Value)) %>% ungroup %>% select(Feature, WD2_Avg) %>% distinct()
WD4 = filter(complete_liverData, Treatment == 'WD4') %>% gather(Feature, Value, 3:578) %>% group_by(Feature) %>% drop_na() %>% mutate(WD4_Avg = mean(Value)) %>% ungroup %>% select(Feature, WD4_Avg) %>% distinct()
WD6 = filter(complete_liverData, Treatment == 'WD6') %>% gather(Feature, Value, 3:578) %>% group_by(Feature) %>% drop_na() %>% mutate(WD6_Avg = mean(Value)) %>% ungroup %>% select(Feature, WD6_Avg) %>% distinct()
WD8 = filter(complete_liverData, Treatment == 'WD8') %>% gather(Feature, Value, 3:578) %>% group_by(Feature) %>% drop_na() %>% mutate(WD8_Avg = mean(Value)) %>% ungroup %>% select(Feature, WD8_Avg) %>% distinct()

changingFeatures = left_join(CHOW8, WD2, by = 'Feature') %>% left_join(., WD4, by = 'Feature') %>% left_join(., WD6, by = 'Feature') %>%
  left_join(., WD8, by = 'Feature') %>% drop_na() %>%
  mutate(WD2_relative_CHOW8 = WD2_Avg/CHOW8_Avg,
         WD4_relative_CHOW8 = WD4_Avg/CHOW8_Avg,
         WD6_relative_CHOW8 = WD6_Avg/CHOW8_Avg,
         WD8_relative_CHOW8 = WD8_Avg/CHOW8_Avg) %>% 
  select(-c(CHOW8_Avg, WD2_Avg, WD4_Avg, WD6_Avg, WD8_Avg)) %>%
  gather(Condition, FC, 2:5) %>%
  filter(FC > 2 | FC < 0.5) %>%
  select(Feature) %>% distinct()
  

  
  
  
  
  
  
  
  
  left_join(., clusters, by = 'Feature') %>%
  ggplot(aes(x = Condition, y = reorder(Feature, Cluster))) + geom_tile(aes(fill = log2(FC))) +
    facet_grid(~Cluster) +
    scale_fill_distiller(palette = 'RdYlBu', na.value="black", limits = c(-7.4, 7.4))



  spread(Condition, FC)

changingSpecies = FC$Feature

FC = rbind(CHOW8, WD2, WD4, WD6, WD8) %>% drop_na() %>% spread(Feature, Value)

library(pheatmap)

pheatmap(complete_liverData[,-c(1,2)], cluster_rows = FALSE)
test = FC[,1:10]

test = select(complete_liverData, changingSpecies)
test = complete_liverData[,c(1:10)]
```



```{r}
# Generate data frame for bubble plot
generate_bubble_data <- function(data) {
  totalLipidByClass = data %>%
  gather(Feature, Value, 3:ncol(.)) %>%
  separate(col = 'Feature', into = c("Class"), sep = "\\.", remove = FALSE, extra = 'drop') %>%
  mutate(RefinedClass = ifelse(grepl("PE[.]O", Feature), "PE_O",
                        ifelse(grepl("PE[.]P", Feature), "PE_P", Class))) %>%
  select(-Class) %>%
  group_by(ID, RefinedClass) %>%
  drop_na() %>%
  mutate(totalLipid = sum(Value)) %>%
  ungroup() %>%
  select(ID, Treatment, RefinedClass, totalLipid) %>%
  distinct() %>%
  group_by(RefinedClass) %>%
  mutate(n_groups = length(unique(Treatment))) %>%
  filter(n_groups == 5) %>%
  ungroup() %>%
  select(-n_groups)

  # Use Dunnett's test to get significance of each lipid class at WD2,4,6,8 relative to control
  totalLipidByClass$Treatment <- as.factor(totalLipidByClass$Treatment)
  lipidClasses = levels(factor(totalLipidByClass$RefinedClass))
  pval_table = data.frame("Comparison" = character(), "pval" = double(), "Median" = double(), 
                          "FC" = double(), "RefinedClass" = character(), stringsAsFactors = FALSE)

  for(i in lipidClasses) {
    result = DunnettTest(totalLipid ~ Treatment, 
                       data = filter(totalLipidByClass, RefinedClass == i), 
                       control = 'Chow8')
    FC = totalLipidByClass %>% 
      filter(RefinedClass == i) %>% 
      group_by(Treatment) %>% 
      mutate(Median = median(totalLipid)) %>% 
      ungroup() %>%
      select(Treatment, RefinedClass, Median) %>% 
      distinct() %>% 
      mutate(FC = Median / filter(., Treatment == 'Chow8')$Median) %>%
      filter(Treatment != 'Chow8') %>% 
      mutate(Comparison = paste(Treatment, "-", "Chow8", sep = "")) %>% 
      select(Comparison, Median, FC, RefinedClass)
  
    # combine the significance and fold-change into single entry
    entry = as.data.frame(result$Chow8) %>% 
      select(pval) %>% 
      tibble::rownames_to_column(var = "Comparison") %>% 
      left_join(., FC, by = "Comparison")

    pval_table = rbind(pval_table, entry)
  }
  return(pval_table)
}
```

```{r}
# Generate dataframe for liver lipidomics bubble plot
pval_table = generate_bubble_data(liverData)
pval_table = pval_table %>% mutate(significant = ifelse(pval < 0.05, "yes", "no"))
```

```{r}
# Liver lipidomics bubble plot of diet vs. fold-change. Fold-change is calculated using the median lipid abundance for each diet. Size of bubble highlights signficance (from Dunnett's test that does post hoc pairwise multiple comparisons procedure)
colors <- c("#A00000", "#00C000", "#5757F9", "#FF6000", "#0000C0", "#C0C000", "#D7B0B0", "#9F044D", 
            "#077E97", "#C5944E", "#034E61", "#FFA040", "#606060", "#fcfc81")

pval_table %>%
  mutate(log2FC = log2(FC)) %>%
  mutate(log10P = -log10(pval)) %>%
  mutate(log10Abundance = log10(Median)) %>%
  arrange(desc(log10Abundance)) %>%
  mutate(Significant = ifelse(pval < 0.05, "yes", "no")) %>%
  ggplot(aes(x=log2FC, y=log10Abundance, size=log10P, fill=RefinedClass)) +
    geom_vline(xintercept = 0, linetype = 'solid', color = 'black') +
    geom_hline(yintercept = c(0, 2, 4, 6), linetype = 'dotted', color = 'grey70', size = 1) +
    geom_point(alpha=0.9, aes(fill = RefinedClass), color = 'black', pch = 21, stroke = 1) +
    scale_size(range = c(5, 20), name="Significance -log10(P)", breaks=c(0.01,0.1,1,5,9)) +
    ylim(0, 7) +
    xlim(-0.5, 5.5) +
    scale_fill_manual(values = colors) +
    facet_grid(~Comparison, scales = 'fixed') +
    labs(x = "log2(Fold-change)", y = "log10(Abundance)")
#ggsave('../figures/lipidomics_liver_bubble_plot.pdf', height = 5.5, width = 18)
```

```{r}
# Generate dataframe for plasma lipidomics bubble plot
pval_table = generate_bubble_data(plasmaData)
pval_table = pval_table %>% mutate(significant = ifelse(pval < 0.05, "yes", "no"))
```

```{r}
# Plasma lipidomics bubble plot of diet vs. fold-change. Fold-change is calculated using the median lipid abundance for each diet. Size of bubble highlights signficance (from Dunnett's test that does post hoc pairwise multiple comparisons procedure)
colors <- c("#A00000", "#00C000", "#5757F9", "#FF6000", "#0000C0", "#C0C000", "#D7B0B0", "#9F044D", 
            "#077E97", "#606060", "#fcfc81")

pval_table %>%
  mutate(log2FC = log2(FC)) %>%
  mutate(log10P = -log10(pval)) %>%
  mutate(log10Abundance = log10(Median)) %>%
  arrange(desc(log10Abundance)) %>%
  mutate(Significant = ifelse(pval < 0.05, "yes", "no")) %>%
  ggplot(aes(x=log2FC, y=log10Abundance, size=log10P, fill=RefinedClass)) +
    geom_vline(xintercept = 0, linetype = 'solid', color = 'black') +
    geom_hline(yintercept = c(0, 2, 4), linetype = 'dotted', color = 'grey70', size = 1) +
    geom_point(alpha=0.9, aes(fill = RefinedClass), color = 'black', pch = 21, stroke = 1) +
    scale_size(range = c(5, 20), name="Significance -log10(P)", breaks=c(1,5,10,15)) +
    xlim(-2, 2) +
    scale_fill_manual(values = colors) +
    facet_grid(~Comparison, scales = 'fixed') +
    labs(x = "log2(Fold-change)", y = "log10(Abundance)")
#ggsave('../figures/lipidomics_plasma_bubble_plot.pdf', height = 5.5, width = 18)
```


