---
title: "Osbpl3 figures"
author: "Timothy Yu"
date: "6/24/24"
output: html_document
---

```{r setup, include=FALSE}
suppressPackageStartupMessages(library(ComplexHeatmap))
library(tidyverse)
library(viridis)
require(cowplot)
theme_set(theme_cowplot())
```

```{r}
# read in Osbpl3 RNA seq FPKM
osbpl3_rna = read.csv('../processed_data/datasets/RNAseq_FPKM.csv', header = TRUE, 
                         stringsAsFactors = FALSE, check.names = FALSE) %>% select(ID, Treatment, Osbpl3)

# read in lipidomics data
liverData = read.csv('../processed_data/datasets/Lipidomics_liver.csv', header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
```

```{r}
osbpl3_rna_lipid = left_join(osbpl3_rna, liverData, by=c('ID', 'Treatment'))
```

```{r}
# first plot osbpl3 as function of diet
osbpl3_rna_lipid %>%
  ggplot(aes(x = Treatment, y = Osbpl3)) +
  geom_boxplot(aes(fill = Treatment), outlier.shape = NA, alpha = 0.6) + 
  geom_point(aes(fill = Treatment), pch = 21, color = 'black', size = 3) +
  scale_fill_viridis(discrete=TRUE)
```
```{r}
# Function to classify lipids based on double bonds
classify_lipid <- function(lipid) {
  # Extract all segments separated by dot or underscore
  segments <- unlist(str_split(lipid, "[._]"))
  
  # Initialize an empty vector to store double bond numbers
  double_bonds <- c()
  
  # Loop through segments to find numbers and handle special 'd' cases
  for (i in 1:length(segments)) {
    if (grepl("^\\d+$", segments[i])) {
      # If the segment is purely numeric
      double_bonds <- c(double_bonds, as.numeric(segments[i]))
    } else if (grepl("^d\\d+$", segments[i]) && i < length(segments) && grepl("^\\d+$", segments[i + 1])) {
      # If the segment is like 'd18' and the next segment is a number
      double_bonds <- c(double_bonds, as.numeric(segments[i + 1]))
      i <- i + 1  # Skip the next segment as it has been included already
    }
  }
  
  # Extract every second number (considering it is always the second number in each block)
  double_bonds <- double_bonds[seq(2, length(double_bonds), by = 2)]
  
  # Sum the double bond numbers
  total_double_bonds <- sum(double_bonds, na.rm = TRUE)
  
  # Classify based on the number of double bonds
  if (total_double_bonds == 0) {
    return("Saturated")
  } else if (total_double_bonds == 1) {
    return("Monounsaturated")
  } else {
    return("Polyunsaturated")
  }
}

test_osbpl3 = osbpl3_rna_lipid %>%
  pivot_longer(cols = -c(ID, Treatment, Osbpl3),
               names_to = "Lipid",
               values_to = "Value") %>%
  mutate(Class = ifelse(grepl("^PE\\.O\\.|^PE\\.P\\.", Lipid),
                              sub("\\.", "_", str_extract(Lipid, "^PE\\..")),
                              str_extract(Lipid, "^[^.]+"))) %>% 
  mutate(Type = sapply(Lipid, classify_lipid))


# DG, PE_P, PC, LPC, FA, LacCer, CER, HexCER, Pe(O), SM, LPE

```

```{r}
test_osbpl3 %>% filter(Class == "FA") %>%
  ggplot(aes(x = Value, y = Osbpl3, color = Type)) +
  geom_point(size=3) +
  scale_color_viridis(discrete = TRUE) +
  labs(x = '', y = 'Osbpl3', title = 'Osbpl3 x FA') +
  facet_wrap(~Type+Lipid, scales='free')
ggsave('../figures/osbpl3/osbpl3_x_fa.pdf', height=15, width=20)
```

```{r}
osbpl3_x_liver_lipid = read.csv(
  '../processed_data/correlations/top50gene_x_liver_lipid.csv'
) %>% 
  filter(Gene == 'Osbpl3') %>%
  mutate(Lipid_class = ifelse(grepl("^PE\\.O\\.|^PE\\.P\\.", Liver_lipid),
                              sub("\\.", "_", str_extract(Liver_lipid, "^PE\\..")),
                              str_extract(Liver_lipid, "^[^.]+"))) %>% drop_na()
```

```{r}
library(readxl)
osbpl3_crispr_data = read_excel('../raw_data/excel/20210623_Exp1_ETV203_Osbpl3.xlsx', 
                                sheet = "Signif Species") %>%
  rename(Liver_lipid = `...1`)

```

```{r}
ggplot(osbpl3_rna_lipid, aes(x =Osbpl3, y =`CE.17.0`)) + geom_point()

```